spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bandai?serverTimezone=Asia/Seoul
    username: root
    password: a1234

server:
  port: 8097
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  config: mybatis/mybatis-config.xml
  mapper-locations: mybatis/mappers/*.xml